version: "3.8"
services:
  backend:
    container_name: mvp-backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
  frontend:
    container_name: mvp-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
