[tool.poetry]
name = "greg-mvp"
version = "0.1.0"
description = "MVP FastAPI backend with domain knowledge and NL->SQL stubs"
authors = ["Andrew Hoban <andrew@example.com>"]
license = "MIT"
packages = [{include = "backend"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.0"}
pydantic = "^2.8.0"
pydantic-settings = "^2.3.0"
loguru = "^0.7.2"
google-cloud-bigquery = "^3.25.0"
httpx = "^0.27.0"
jinja2 = "^3.1.4"
plotly = "^5.22.0"
python-dotenv = "^1.0.1"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"
ruff = "^0.5.5"
black = "^24.4.2"
isort = "^5.13.2"
mypy = "^1.10.0"
anyio = "^4.4.0"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "ASYNC"]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
namespace_packages = true
explicit_package_bases = true

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"